name: Test GRA Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: |
        go mod download
        
    - name: Run unit tests
      run: go test -v ./...
      
    # This step will run only after the migration is complete
    - name: Run GRA framework tests
      run: |
        if go test -v ./tests/unit/gra_test.go 2>/dev/null; then
          echo "GRA framework migration verified successfully!"
        else
          echo "GRA framework migration has not been completed yet."
          echo "This is expected if you're still using the internal core package."
        fi
      continue-on-error: true
        
    - name: Run API integration tests
      run: |
        # Start server in background
        go run cmd/core-api/main.go &
        # Wait for server to start
        sleep 5
        # Run curl tests
        curl -s http://localhost:8080/ | grep "success" || { echo "API test failed"; exit 1; }
        # Kill server
        pkill -f "go run cmd/core-api/main.go" || true
        
    - name: Coverage report
      run: go test -cover ./...
